name: SPAA
description: Association loi 1901 dédiée à l’accueil, aux soins et à l’adoption
  des animaux abandonnés.
opening: Ouvert du mardi au dimanche, 10h–18h
phone: "? ? ? ? ?"
email: ?????
address: 4 rue des mouettes 14000 Caen
don_url: "#"
legal_url: "#"
